Create Table Books(
	Book_ID	serial	primary key,
	Title	Varchar(100),	
	Author	Varchar(100),	
	Genre	Varchar(100),	
	Published_Year	INT	,
	Price	Numeric(10,2),	
	Stock	INt	

);
drop table customers;
Create Table customers(
		Customer_ID	serial primary   key,
		Name	Varchar(100),
		Email	Varchar(100),
		Phone	INT,
		City	Varchar(100),
		Country	Varchar(100)
);

Create Table Orders(
	Order_ID	Serial	Primary key	,		
	Customer_ID	INT	References 	Customers(Customer_ID),	
	Book_ID	INT	References 	Books(	Book_ID),
	Order_Date	Date,				
	Quantity	INT	,			
	Total_Amount	Numeric(10,2)				
);
--Import Data into Books Table
Select * from books;
--Import Data into customers Table
Select * from customers;
--Import Data into orders Table
Select * from orders;
-- 1.)Reterive all the books in the fiction genere
 select * from books
 Where genre ='Fiction';
 -- 2.) Find books published after the year 1995
 select * from books
 where published_year >1950;
-- 3.) List all the customers from canada
 select * from customers
 where country = 'Canada';
--4.) Show Orders Placed in November 2023
select * from orders
where order_date Between '2023-11-01' And '2023-11-30';
--5.) Retrive the total stock of books avaialbe
select sum(stock)  As total_sum from Books;
--6)Find details of most expensive books
 select * from books order by price desc limit 1;
--7) show all customers odered more than 1 quantity of book
select * from orders
where quantity > 1;
--8) Retrive all orders where total amount exceeds 20
 select * from orders
 where total_amount >20;
--9) List all geners available in the book table
select Distinct (genre) from books;
--10) Find the book with lowest stock
--select min(stock) from books limit 1;
select * from books order by stock asc limit 1;
-- 11) Total revenue generated by all orders
select sum(total_amount) As Revenue from orders;
-- 12) Retrive total number of books sold for each genre
Select b.genre , sum(o.quantity) As total_sold
from orders o
join books b
on  b.book_id=o.book_id
group by genre;
--13) Find the average price of book in the 'fantasy' genre
Select avg(price) from books
where genre = 'Fanatsy';
--14) Find the most frequently ordered book
Select o.book_id , b.title , count(o.order_id) from orders o
join books b on o.book_id=b.book_id
group by o.book_id , b.title
order by count(o.order_id) desc limit 1;
--15) show the most 3 expensive books of 'fantasy' genre
select * from books
where genre ='Fantasy'
order by price desc limit 3;
--16) Total quantity of books sold by each author
select  b.author ,sum(o.quantity)
from orders o join books b
on b.book_id = o.book_id
group by b.author;
--16) List the cities where customers who spent over 30 are located
select  distinct(c.city) , o.total_amount from orders o
join customers c
on o.customer_id = c.customer_id
where o.total_amount >=30;
-- 17) find the customers who spent most on orders
select c.name,c.customer_id , sum(o.total_amount) As spent_t from orders o
join customers c
on o.customer_id = c.customer_id
group by  c.name,c.customer_id  
order by spent_t desc  limit 1;
